software_groups: &software
  - base

jobs:
  sysdig-shellshock:
    builder: make
    base: ubuntu:12.04
    software_groups: *software
    packages:
      - type: debian
        name: sysdig-shellshock
        depends:
          - sysdig
          - runit-common
        target: install
        repos:
          - mxm-public
