software_groups: &software
  - base

jobs:
  sysdig_shellshock:
    builder: make
    base: ubuntu:12.04
    software_groups: *software
    packages:
      - type: debian
        name: sysdig_shellshock
        version: 0.0.1
        depends:
          - sysdig
          - runit-common
        target: install
        repos:
          - mxm-public
